# Generated by Django 3.1.6 on 2021-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_reg',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('service_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
