# Generated by Django 3.1.6 on 2021-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_reg',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
