# Generated by Django 3.1.6 on 2021-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep', '0002_auto_20210420_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_reg',
            name='ser_user_name',
            field=models.CharField(default='NULL22', max_length=30),
        ),
    ]
