# Generated by Django 3.1.6 on 2021-04-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep', '0003_service_reg_ser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_service_provider',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
